/**
 * @canonical
 * Hypothesis Runtime Contracts
 * Hypotheses are investigable claims generated by the AI, not truth. They exist to direct exploration.
 */

export type HypothesisType =
  | 'TRUST_ESCALATION_SUSPICION'
  | 'FORGED_LINEAGE_SUSPICION'
  | 'ANTI_BOT_DIVERGENCE'
  | 'OWNERSHIP_MUTATION_ANOMALY'
  | 'AUTH_INCONSISTENCY'
  | 'PRIVILEGE_ESCALATION_SUSPICION'
  | 'TENANT_ISOLATION_BREACH';

export type HypothesisStatus = 'FORMULATED' | 'EVALUATING' | 'ESCALATED' | 'PROVEN_TRUE' | 'PROVEN_FALSE' | 'EXPIRED';

export interface HypothesisEvidence {
  evidenceType: 'OBSERVATION' | 'CONTRADICTION' | 'TRUST_CONFLICT' | 'TEMPORAL_ANOMALY';
  referenceId: string;
  weight: number;
}

export interface HypothesisConfidence {
  baseScore: number;
  decayRate: number; // Confidence decays if not proven within a temporal window
  lastCalculatedAt: number;
}

export interface HypothesisEscalation {
  escalationId: string;
  escalatedAtTs: number;
  reason: string;
  targetAuthority: 'HUMAN_REVIEW' | 'ACTIVE_MUTATION_QUEUE' | 'DEEP_REPLAY_ENGINE';
}

export interface InvestigativePath {
  pathId: string;
  hypothesisId: string;
  plannedExplorationSteps: string[];
  executedSteps: string[];
  pathConfidence: number;
}

export interface Hypothesis {
  id: string;
  type: HypothesisType;
  description: string;
  status: HypothesisStatus;
  confidence: HypothesisConfidence;
  evidence: HypothesisEvidence[];
  investigativePaths: InvestigativePath[];
  escalationState?: HypothesisEscalation;
  formulatedAtTs: number;
  expiresAtTs?: number;
}
