/**
 * @canonical
 * InvestigationCandidate Runtime Contracts
 * Hypotheses are investigable claims generated by the AI, not truth. They exist to direct exploration.
 */

export type InvestigationCandidateType =
  | 'TRUST_ESCALATION_SUSPICION'
  | 'FORGED_LINEAGE_SUSPICION'
  | 'ANTI_BOT_DIVERGENCE'
  | 'OWNERSHIP_MUTATION_ANOMALY'
  | 'AUTH_INCONSISTENCY'
  | 'PRIVILEGE_ESCALATION_SUSPICION'
  | 'TENANT_ISOLATION_BREACH';

export type InvestigationCandidateStatus = 'FORMULATED' | 'EVALUATING' | 'ESCALATED' | 'PROVEN_TRUE' | 'PROVEN_FALSE' | 'EXPIRED';

export interface InvestigationCandidateEvidence {
  evidenceType: 'OBSERVATION' | 'CONTRADICTION' | 'TRUST_CONFLICT' | 'TEMPORAL_ANOMALY';
  referenceId: string;
  weight: number;
}

export interface InvestigationCandidateConfidence {
  baseScore: number;
  decayRate: number; // Confidence decays if not proven within a temporal window
  lastCalculatedAt: number;
}

export interface InvestigationCandidateEscalation {
  escalationId: string;
  escalatedAtTs: number;
  reason: string;
  targetAuthority: 'HUMAN_REVIEW' | 'ACTIVE_MUTATION_QUEUE' | 'DEEP_REPLAY_ENGINE';
}

export interface InvestigativePath {
  pathId: string;
  candidateId: string;
  plannedExplorationSteps: string[];
  executedSteps: string[];
  pathConfidence: number;
}

export interface InvestigationCandidate {
  id: string;
  type: InvestigationCandidateType;
  description: string;
  status: InvestigationCandidateStatus;
  confidence: InvestigationCandidateConfidence;
  evidence: InvestigationCandidateEvidence[];
  investigativePaths: InvestigativePath[];
  escalationState?: InvestigationCandidateEscalation;
  formulatedAtTs: number;
  expiresAtTs?: number;
}
